#!/bin/bash

NODE=`which node`
NODEJS=`which nodejs`
IOJS=`which iojs`

if [[ -n $NODE ]]; then
  $NODE ./index.js
elif [[ -n $NODEJS ]]; then
  $NODEJS ./index.js
elif [[ -n $IOJS ]]; then
  $IOJS ./index.js
fi
